name: Angular CI/CD Deploy

on:
  push:
    branches:
      - master  # triggers on push to master
  workflow_dispatch:
    inputs:
    environment:
      description: 'Environment to deploy'
      required: true
      default: 'production'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build

      - name: Deploy to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USER }}
          password: ${{ secrets.HOSTINGER_PASS }}
          local-dir: ./dist/buy-bulk/
          server-dir: ${{ secrets.HOSTINGER_PATH }}
          protocol: ftps
          dry-run: false
